services:
  - type: web
    name: employee_tracking
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn employee_tracking.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: employee_tracking.settings
